#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : meld
Version  : 3.22.0
Release  : 51
URL      : https://download.gnome.org/sources/meld/3.22/meld-3.22.0.tar.xz
Source0  : https://download.gnome.org/sources/meld/3.22/meld-3.22.0.tar.xz
Summary  : Visual diff and merge tool
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: compat-gtksourceview-soname3
Requires: pygobject
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : glib
BuildRequires : gtk3
BuildRequires : intltool
BuildRequires : libxml2

%description
Meld is the visual diff and merge tool of GNOME, targeted at developers. It
allows users to compare two or three files or directories visually,
color-coding the different lines.

%prep
%setup -q -n meld-3.22.0
cd %{_builddir}/meld-3.22.0
pushd ..
cp -a meld-3.22.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663965893
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/meld
cp %{_builddir}/meld-%{version}/COPYING %{buildroot}/usr/share/package-licenses/meld/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/meld-%{version}/meld/vc/COPYING %{buildroot}/usr/share/package-licenses/meld/14c4e1f2e383319099e47e974f26fba40e0c975d || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
## Remove excluded files
rm -f %{buildroot}*/usr/share/glib-2.0/schemas/gschemas.compiled
rm -f %{buildroot}*/usr/share/icons/hicolor/icon-theme.cache
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
