#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : meld
Version  : 3.18.1
Release  : 3
URL      : https://download.gnome.org/sources/meld/3.18/meld-3.18.1.tar.xz
Source0  : https://download.gnome.org/sources/meld/3.18/meld-3.18.1.tar.xz
Summary  : Visual diff and merge tool
Group    : Development/Tools
License  : BSD-2-Clause CC-BY-SA-3.0 GPL-2.0 GPL-2.0+
Requires: meld-bin
Requires: meld-python3
Requires: meld-data
Requires: meld-license
Requires: meld-locales
Requires: meld-man
Requires: meld-python
BuildRequires : glib
BuildRequires : gtk3
BuildRequires : intltool
BuildRequires : libxml2
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
About Meld
==========
Meld is a visual diff and merge tool targeted at developers. Meld helps you
compare files, directories, and version controlled projects. It provides
two- and three-way comparison of both files and directories, and supports
many version control systems including Git, Mercurial, Bazaar and Subversion.

%package bin
Summary: bin components for the meld package.
Group: Binaries
Requires: meld-data
Requires: meld-license
Requires: meld-man

%description bin
bin components for the meld package.


%package data
Summary: data components for the meld package.
Group: Data

%description data
data components for the meld package.


%package doc
Summary: doc components for the meld package.
Group: Documentation
Requires: meld-man

%description doc
doc components for the meld package.


%package license
Summary: license components for the meld package.
Group: Default

%description license
license components for the meld package.


%package locales
Summary: locales components for the meld package.
Group: Default

%description locales
locales components for the meld package.


%package man
Summary: man components for the meld package.
Group: Default

%description man
man components for the meld package.


%package python
Summary: python components for the meld package.
Group: Default
Requires: meld-python3

%description python
python components for the meld package.


%package python3
Summary: python3 components for the meld package.
Group: Default
Requires: python3-core

%description python3
python3 components for the meld package.


%prep
%setup -q -n meld-3.18.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529028039
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/meld
cp COPYING %{buildroot}/usr/share/doc/meld/COPYING
cp data/icons/COPYING %{buildroot}/usr/share/doc/meld/data_icons_COPYING
cp data/icons/COPYING_CCBYSA3 %{buildroot}/usr/share/doc/meld/data_icons_COPYING_CCBYSA3
cp meld/vc/COPYING %{buildroot}/usr/share/doc/meld/meld_vc_COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
%find_lang meld

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/meld

%files data
%defattr(-,root,root,-)
%exclude /usr/share/glib-2.0/schemas/gschemas.compiled
%exclude /usr/share/icons/hicolor/icon-theme.cache
/usr/share/appdata/meld.appdata.xml
/usr/share/applications/meld.desktop
/usr/share/glib-2.0/schemas/org.gnome.meld.gschema.xml
/usr/share/icons/HighContrast/scalable/apps/meld.svg
/usr/share/icons/hicolor/16x16/actions/meld-change-apply-left.png
/usr/share/icons/hicolor/16x16/actions/meld-change-apply-right.png
/usr/share/icons/hicolor/16x16/actions/meld-change-copy.png
/usr/share/icons/hicolor/16x16/actions/meld-change-delete.png
/usr/share/icons/hicolor/16x16/apps/meld-version-control.png
/usr/share/icons/hicolor/16x16/apps/meld.png
/usr/share/icons/hicolor/22x22/apps/meld.png
/usr/share/icons/hicolor/32x32/apps/meld.png
/usr/share/icons/hicolor/48x48/apps/meld-version-control.png
/usr/share/icons/hicolor/48x48/apps/meld.png
/usr/share/icons/hicolor/scalable/apps/meld.svg
/usr/share/meld/icons/COPYING
/usr/share/meld/icons/COPYING_CCBYSA3
/usr/share/meld/icons/emblem-meld-newer-file.png
/usr/share/meld/icons/filter-ignored-24.png
/usr/share/meld/icons/filter-modified-24.png
/usr/share/meld/icons/filter-nonvc-24.png
/usr/share/meld/icons/filter-normal-24.png
/usr/share/meld/icons/vc-add-24.png
/usr/share/meld/icons/vc-checkout-24.png
/usr/share/meld/icons/vc-commit-24.png
/usr/share/meld/icons/vc-push-24.png
/usr/share/meld/icons/vc-remove-24.png
/usr/share/meld/icons/vc-resolve-24.png
/usr/share/meld/icons/vc-update-24.png
/usr/share/meld/meld.css
/usr/share/meld/styles/meld-base.xml
/usr/share/meld/styles/meld-dark.xml
/usr/share/meld/ui/EditableList.ui
/usr/share/meld/ui/application.ui
/usr/share/meld/ui/appmenu-fallback.xml
/usr/share/meld/ui/dirdiff-ui.xml
/usr/share/meld/ui/dirdiff.ui
/usr/share/meld/ui/filediff-ui.xml
/usr/share/meld/ui/filediff.ui
/usr/share/meld/ui/findbar.ui
/usr/share/meld/ui/meldapp-ui.xml
/usr/share/meld/ui/meldapp.ui
/usr/share/meld/ui/patch-dialog.ui
/usr/share/meld/ui/preferences.ui
/usr/share/meld/ui/shortcuts.ui
/usr/share/meld/ui/tab-placeholder.ui
/usr/share/meld/ui/vcview-ui.xml
/usr/share/meld/ui/vcview.ui
/usr/share/mime/packages/meld.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/meld-3.18.1/NEWS
/usr/share/help/C/meld/command-line.page
/usr/share/help/C/meld/file-changes.page
/usr/share/help/C/meld/file-filters.page
/usr/share/help/C/meld/file-mode.page
/usr/share/help/C/meld/flattened-view.page
/usr/share/help/C/meld/folder-mode.page
/usr/share/help/C/meld/index.page
/usr/share/help/C/meld/introduction.page
/usr/share/help/C/meld/keyboard-shortcuts.page
/usr/share/help/C/meld/legal.xml
/usr/share/help/C/meld/missing-functionality.page
/usr/share/help/C/meld/preferences.page
/usr/share/help/C/meld/resolving-conflicts.page
/usr/share/help/C/meld/text-filters.page
/usr/share/help/C/meld/vc-mode.page
/usr/share/help/C/meld/vc-supported.page

%files license
%defattr(-,root,root,-)
/usr/share/doc/meld-3.18.1/COPYING
/usr/share/doc/meld/COPYING
/usr/share/doc/meld/data_icons_COPYING
/usr/share/doc/meld/data_icons_COPYING_CCBYSA3
/usr/share/doc/meld/meld_vc_COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/meld.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f meld.lang
%defattr(-,root,root,-)

